### ISSUE TITLE
[Feature Request] Add min / max reduction

### ISSUE THREAD

**Issue by fzimmermann89** [pytorch/tensordict#1012]
## Motivation

For supporting [einops](https://github.com/arogozhnikov/einops), tensordict would need a min/max reduction.

## Solution

Similiar to mean, etc. the min and max should be implemented in https://github.com/pytorch/tensordict/blob/main/tensordict/base.py by calling `_cast_reduction`

I did not find any issue or explaination why this is missing..

**Comment by vmoens** [comment]
on it!

**Comment by vmoens** [comment]
I'm working on this and I have a question for you:
what would be the most intuitive API:
1. `min(dim=dim)` returns only the values. This breaks with `torch.min(tensor, dim)` which returns a namedtuple but feels "natural" otherwise
2. `min(dim=dim)` returns a tensordict where the leaves are `("key0", "key1", "values")` for the values and `("key0", "key1", "indices")` for the indices
3. `min(dim=dim)` returns a tensordict where the leaves are `("values", "key0", "key1")` for the values and `("indices", "key0", "key1")` for the indices
4. `min(dim=dim)` returns a _tensorclass_ with fields `indices` and `values`, where the leaves are `("key0", "key1")` for each
5. A namedtuple, as it is the case with pytorch

**Comment by fzimmermann89** [comment]
If it were up to me, I would prefer `.amin` and` .amax`, both supporting multiple dimensions and only returning the value.

**Comment by vmoens** [comment]
Cool I tried to do that. LMK if these changes make sense

**Comment by fzimmermann89** [comment]
Is amin() here min().values? In torch, those two behave differently in the backward pass afaik

**Comment by vmoens** [comment]
Oh good point, I should use amin directly then

**Comment by vmoens** [comment]
closed by #1057
